/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/57rgaX9aAHs
 */
import { CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"

export function FormComponent() {
  return (
    <Card className="w-full max-w-lg">
      <CardHeader>
        <div>Write a Report</div>
        <p className="text-sm leading-none mt-1 text-gray-500 dark:text-gray-400">
          Your daily report will be shared with your team.
        </p>
      </CardHeader>
      <CardContent className="grid gap-4">
        <div className="grid gap-1.5">
          <Label htmlFor="title">Title</Label>
          <Input id="title" placeholder="Title" />
        </div>
        <div className="grid gap-1.5">
          <Label htmlFor="body">Body</Label>
          <Textarea id="body" placeholder="Body" />
        </div>
        <div className="grid gap-1.5">
          <Label htmlFor="date">Date</Label>
          <Input id="date" type="date" />
        </div>
      </CardContent>
      <CardFooter>
        <Button size="sm">Submit</Button>
      </CardFooter>
    </Card>
  )
}
