/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/tdM9pAoibrk
 */
import Link from "next/link"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"
import { CardContent, Card } from "@/components/ui/card"

export function TableComponent() {
  return (
    <div className="flex flex-col w-full min-h-screen">
      <header className="flex items-center h-16 px-4 border-b shrink-0 md:px-6">
        <div className="flex items-center gap-4">
          <Link className="text-lg font-bold" href="#">
            Daily Report
          </Link>
        </div>
      </header>
      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <Card>
          <CardContent className="p-6">
            <div className="overflow-hidden border border-gray-200 rounded-lg dark:border-gray-800">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Title</TableHead>
                    <TableHead>Date</TableHead>
                    <TableHead>User</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell className="font-medium">Daily Report 1</TableCell>
                    <TableCell>2023-08-21</TableCell>
                    <TableCell>John Doe</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Daily Report 2</TableCell>
                    <TableCell>2023-08-22</TableCell>
                    <TableCell>Jane Smith</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Daily Report 3</TableCell>
                    <TableCell>2023-08-23</TableCell>
                    <TableCell>Adam Johnson</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Daily Report 4</TableCell>
                    <TableCell>2023-08-24</TableCell>
                    <TableCell>Susan Chang</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell className="font-medium">Daily Report 5</TableCell>
                    <TableCell>2023-08-25</TableCell>
                    <TableCell>Emily Wilson</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
